### PR TITLE
Deprecate CrossVersion.Disabled (was make CrossVersion.Disabled stable)

### LINKED ISSUE #4975: stable identifier required, but ``sbt.`package`.CrossVersion.Disabled`` found.
## steps

Scala.JS build using sbt 1.3.0-RC4

```scala
  def scalaJSMapped(cross: CrossVersion): CrossVersion = cross match {
    case CrossVersion.Disabled =>
      CrossVersion.constant("sjs" + currentBinaryVersion)
    case cross: sbt.librarymanagement.Constant =>
      cross.withValue("sjs" + currentBinaryVersion + "_" + cross.value)
    case cross: CrossVersion.Binary =>
      cross.withPrefix("sjs" + currentBinaryVersion + "_" + cross.prefix)
    case cross: CrossVersion.Full =>
      cross.withPrefix("sjs" + currentBinaryVersion + "_" + cross.prefix)
  }
```

## problem

```
[error] /Users/eed3si9n/work/scala-js/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSCrossVersion.scala:34:23: stable identifier required, but sbt.`package`.CrossVersion.Disabled found.
[error]     case CrossVersion.Disabled =>
[error]                       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

## expectation

No errors.

## notes
 
- https://github.com/sbt/librarymanagement/pull/121 (https://github.com/sbt/librarymanagement/pull/103) added `final val Disabled = sbt.librarymanagement.Disabled` but it was just a companion object
- https://github.com/sbt/librarymanagement/pull/280 actually made it `final val Disabled = sbt.librarymanagement.Disabled()`, but this broke Cat's build.
   `[cats] [error] java.lang.NoSuchMethodError: sbt.librarymanagement.CrossVersion$.Disabled()Lsbt/librarymanagement/Disabled$;`
- https://github.com/sbt/librarymanagement/pull/290 changed to `final def Disabled = sbt.librarymanagement.Disabled` and `object Disabled extends sbt.librarymanagement.Disabled`, but this broke Scala.JS as above.

### LINKED ISSUE #4977: [1.2.x] CrossVersion.Disabled doesn't work
## migration note

`CrossVersion.Disabled` doesn't work as expected in sbt 1.0.x ~ 1.2.x.

We recommend plugin authors to use `CrossVersion.disabled` instead. For pattern matching, you can either check equality with `CrossVersion.disabled` or type match with `case _: sbt.librarymanagement.Disabled`.

## steps 1

```scala
CrossVersion(CrossVersion.Disabled, "1.0.0", "1.0")
```

## problem 1

It doesn't compile.

```scala
<console>:15: error: type mismatch;
 found   : sbt.librarymanagement.Disabled.type
 required: sbt.librarymanagement.CrossVersion
       CrossVersion(CrossVersion.Disabled, "1.0.0", "1.0")
```

## steps 2

```scala
scala> val currentBinaryVersion = "1.0"
currentBinaryVersion: String = 1.0

scala>   def scalaJSMapped(cross: CrossVersion): CrossVersion = cross match {
           case CrossVersion.Disabled =>
             CrossVersion.constant("sjs" + currentBinaryVersion)
           case cross: sbt.librarymanagement.Constant =>
             cross.withValue("sjs" + currentBinaryVersion + "_" + cross.value)
           case cross: CrossVersion.Binary =>
             cross.withPrefix("sjs" + currentBinaryVersion + "_" + cross.prefix)
           case cross: CrossVersion.Full =>
             cross.withPrefix("sjs" + currentBinaryVersion + "_" + cross.prefix)
         }
scalaJSMapped: (cross: sbt.CrossVersion)sbt.CrossVersion

scala> scalaJSMapped(CrossVersion.disabled)
```

From https://github.com/scala-js/scala-js/blob/7c502f61c87735898c2293cb937eee8f55ad8686/sbt-plugin/src/main/scala/org/scalajs/sbtplugin/ScalaJSCrossVersion.scala

## problem 2

```scala
scala> scalaJSMapped(CrossVersion.disabled)
scala.MatchError: Disabled() (of class sbt.librarymanagement.Disabled)
  at .scalaJSMapped(<console>:15)
  ... 36 elided
```

## expectation

```scala
scala> CrossVersion(CrossVersion.Disabled, "1.0.0", "1.0")
res3: Option[String => String] = None

scala> scalaJSMapped(CrossVersion.disabled)
res5: sbt.CrossVersion = Constant(sjs1.0)
```

## notes

This will be fixed in 1.3.0, but it doesn't currently work in 1.2.x.

- sbt/librarymanagement#121 added `final val Disabled = sbt.librarymanagement.Disabled` but it was just a companion object
- (only available in 1.3.0-x) sbt/librarymanagement#280 actually made it `final val Disabled = sbt.librarymanagement.Disabled()`, but this broke Cat's build that was calling `CrossVersion.Disabled()`
- sbt/librarymanagement#290 changed to `final def Disabled = sbt.librarymanagement.Disabled` and `object Disabled extends sbt.librarymanagement.Disabled`, but this caused #4975
- sbt/librarymanagement#316 changes back to `final val Disabled = sbt.librarymanagement.Disabled` (but because we changed the companion object in sbt/librarymanagement#290 that's ok)

### PR DESCRIPTION
**Pull request by eed3si9n**
## migration note

`CrossVersion.Disabled` did not work as expected in sbt 1.0.x ~ 1.2.x.

We recommend using `CrossVersion.disabled` instead. For pattern matching, you can either check equality with `CrossVersion.disabled` or type match with `case _: sbt.librarymanagement.Disabled`.

## original PR

Fixes https://github.com/sbt/sbt/issues/4975
Fixes https://github.com/sbt/sbt/issues/4977

This makes `CrossVersion.Disabled` a stable identifier by reverting `final def` back to `final val`.

This is to fix Scala.JS build

```
[error] ScalaJSCrossVersion.scala:34:23: stable identifier required, but sbt.`package`.CrossVersion.Disabled found.
[error]     case CrossVersion.Disabled =>
[error]                       ^
[error] one error found
[error] (Compile / compileIncremental) Compilation failed
```

### notes

- #121 added `final val Disabled = sbt.librarymanagement.Disabled` but it was just a companion object
- (only available in 1.3.0-x) #280 actually made it `final val Disabled = sbt.librarymanagement.Disabled()`, but this broke Cat's build that was calling `CrossVersion.Disabled()`
- #290 changed to `final def Disabled = sbt.librarymanagement.Disabled` and `object Disabled extends sbt.librarymanagement.Disabled`
- This changes back to `final val Disabled = sbt.librarymanagement.Disabled` (but because we changed the companion object in #290 that's ok)

### CODE REVIEW

**Comment by typesafe-tools** [comment]
To validate this pull request against other sbt modules, please visit <A HREF="https://jenkins.scala-sbt.org:8592/job/sbt-validator/parambuild/?sbt=develop&zinc=develop&io=develop&librarymanagement=pull/316/head&util=develop&website=develop&deploy_to_bintray=false&run_sbt_community=false&verbose_dbuild=false&community_verbose=false">this link.</A>

**Review by dwijnand — APPROVED** [review]
Ek.  What a journey my mistake has been... sorry.

LGTM, thanks for preserving my change.

**Comment by eed3si9n** [comment]
Given that `CrossVersion.Disabled` is used in the wild, maybe I should also retroactively create a bug and deprecate upper case `Disabled` in favor of `CrossVersion.disabled` for sbt 1.2.x users.
